/* ------------------------------------------------------------------
   기본 단어장 — 수능 필수 영단어 샘플 60개
   앱을 처음 열었을 때 바로 학습을 시작할 수 있도록 시드로 넣는다.
   pos: n(명사) v(동사) a(형용사) ad(부사)
------------------------------------------------------------------ */

export const SEED_WORDS = [
  { word: "abandon", meaning: "버리다, 포기하다", pos: "v" },
  { word: "abundant", meaning: "풍부한, 많은", pos: "a" },
  { word: "absorb", meaning: "흡수하다, 몰두시키다", pos: "v" },
  { word: "abstract", meaning: "추상적인; 요약", pos: "a" },
  { word: "accurate", meaning: "정확한", pos: "a" },
  { word: "acquire", meaning: "얻다, 습득하다", pos: "v" },
  { word: "adapt", meaning: "적응하다, 조정하다", pos: "v" },
  { word: "adopt", meaning: "채택하다, 입양하다", pos: "v" },
  { word: "adequate", meaning: "충분한, 적절한", pos: "a" },
  { word: "afford", meaning: "~할 여유가 있다", pos: "v" },
  { word: "aggressive", meaning: "공격적인, 적극적인", pos: "a" },
  { word: "alter", meaning: "바꾸다, 변경하다", pos: "v" },
  { word: "ambiguous", meaning: "애매한, 모호한", pos: "a" },
  { word: "anticipate", meaning: "예상하다, 기대하다", pos: "v" },
  { word: "apparent", meaning: "명백한, 겉보기의", pos: "a" },
  { word: "appropriate", meaning: "적절한, 알맞은", pos: "a" },
  { word: "approximately", meaning: "대략, 약", pos: "ad" },
  { word: "arbitrary", meaning: "임의의, 제멋대로인", pos: "a" },
  { word: "assess", meaning: "평가하다, 가늠하다", pos: "v" },
  { word: "assume", meaning: "가정하다, 떠맡다", pos: "v" },
  { word: "attribute", meaning: "~탓으로 돌리다; 속성", pos: "v" },
  { word: "authentic", meaning: "진짜의, 진정한", pos: "a" },
  { word: "benefit", meaning: "이익, 혜택; 이롭다", pos: "n" },
  { word: "capable", meaning: "~할 수 있는, 유능한", pos: "a" },
  { word: "cease", meaning: "그치다, 중단하다", pos: "v" },
  { word: "coherent", meaning: "일관된, 조리 있는", pos: "a" },
  { word: "comprehend", meaning: "이해하다", pos: "v" },
  { word: "comprehensive", meaning: "포괄적인, 종합적인", pos: "a" },
  { word: "conceal", meaning: "숨기다, 감추다", pos: "v" },
  { word: "consequence", meaning: "결과, 영향", pos: "n" },
  { word: "considerable", meaning: "상당한, 많은", pos: "a" },
  { word: "constant", meaning: "끊임없는, 일정한", pos: "a" },
  { word: "contemporary", meaning: "현대의, 동시대의", pos: "a" },
  { word: "crucial", meaning: "결정적인, 중대한", pos: "a" },
  { word: "deliberate", meaning: "고의의, 신중한", pos: "a" },
  { word: "demonstrate", meaning: "증명하다, 보여주다", pos: "v" },
  { word: "deprive", meaning: "빼앗다, 박탈하다", pos: "v" },
  { word: "diminish", meaning: "줄이다, 감소하다", pos: "v" },
  { word: "distinct", meaning: "뚜렷한, 별개의", pos: "a" },
  { word: "diverse", meaning: "다양한", pos: "a" },
  { word: "dominate", meaning: "지배하다, 우세하다", pos: "v" },
  { word: "eliminate", meaning: "제거하다, 없애다", pos: "v" },
  { word: "emerge", meaning: "나타나다, 드러나다", pos: "v" },
  { word: "emphasize", meaning: "강조하다", pos: "v" },
  { word: "enhance", meaning: "향상시키다, 높이다", pos: "v" },
  { word: "evident", meaning: "분명한, 명백한", pos: "a" },
  { word: "exaggerate", meaning: "과장하다", pos: "v" },
  { word: "exceed", meaning: "초과하다, 넘어서다", pos: "v" },
  { word: "explicit", meaning: "명백한, 분명한", pos: "a" },
  { word: "extract", meaning: "추출하다, 뽑아내다", pos: "v" },
  { word: "fundamental", meaning: "근본적인, 기본의", pos: "a" },
  { word: "generate", meaning: "만들어내다, 발생시키다", pos: "v" },
  { word: "genuine", meaning: "진짜의, 진심의", pos: "a" },
  { word: "hypothesis", meaning: "가설", pos: "n" },
  { word: "identical", meaning: "동일한, 똑같은", pos: "a" },
  { word: "implement", meaning: "시행하다; 도구", pos: "v" },
  { word: "indicate", meaning: "나타내다, 가리키다", pos: "v" },
  { word: "inevitable", meaning: "피할 수 없는, 필연적인", pos: "a" },
  { word: "integrate", meaning: "통합하다", pos: "v" },
  { word: "reluctant", meaning: "꺼리는, 마지못한", pos: "a" },
];

export const SEED_DECK_NAME = "수능 필수 60";
